filebeat.inputs:
  - type: log
    paths:
      - /var/harvested_logs/api/api.json
    fields:
      log_type: "api-log"
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

  - type: log
    paths:
      - /var/harvested_logs/email_sender/email_sender.json
    fields:
      log_type: "email_sender-log"
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

  - type: log
    paths:
      - /var/harvested_logs/api/uvicorn.json
    fields.log_type: "uvicorn-log"
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

  - type: log
    paths:
      - /var/harvested_logs/nginx/access-log.json
    fields.log_type: "nginx-log"
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true


processors:
  - drop_fields:
      fields: [ "agent", "ecs", "input", "host" ]
      ignore_missing: true

  - copy_fields:
      fields:
        - from: log.level
          to: level
      fail_on_error: false
      ignore_missing: true

  - copy_fields:
      fields:
        - from: log.logger
          to: logger
      fail_on_error: false
      ignore_missing: true

  - drop_fields:
      when.contains.log_type: api-log
      fields: [ "log", "process" ]
      ignore_missing: true

  - drop_fields:
      when.contains.log_type: email_sender-log
      fields: [ "log", "process" ]
      ignore_missing: true


# Настройка Kibana
setup.kibana.host: "${KIBANA_HOST}"
setup.kibana.protocol: http

# Настройка Elasticsearch
output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  index: "notifications-%{[log_type]}-%{+yyyy.MM.dd}"

## Для отладки вместо "output.elasticsearch"
#output.console:
#  pretty: true

# Отключение "Index Lifecycle Management"
setup.ilm.enabled: false

setup.template:
  name: 'api-log'
  pattern: 'notifications-api-log-*'
  fields: "fields.yml"
  overwrite: true
  enabled: true