# Generated by Django 3.2.9 on 2022-06-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='uuid Платежа с Yookassa'),
        ),
    ]
