"""add unique constr to UserRoles

Revision ID: 17d623045bba
Revises: 6c4ce991fdda
Create Date: 2022-06-08 11:00:53.068214

"""
from alembic import op
import sqlalchemy as sa
import auth_api
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17d623045bba'
down_revision = '6c4ce991fdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_users_roles_link', 'links_users_roles', ['users_uuid', 'roles_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_users_roles_link', 'links_users_roles', type_='unique')
    # ### end Alembic commands ###
