"""add date_exp to user role

Revision ID: 6c4ce991fdda
Revises: 01f2a1ba7867
Create Date: 2022-06-06 21:36:00.081234

"""
from alembic import op
import sqlalchemy as sa
import auth_api
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c4ce991fdda'
down_revision = '01f2a1ba7867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'links_users_roles', sa.Column('date_expiration', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links_users_roles', 'date_expiration')
    # ### end Alembic commands ###
