cycles_delay: 60

kafka:
  bootstrap_servers: kafka:9092
  auto_offset_reset: earliest
  enable_auto_commit: false
  group_id: etl_service
  topics:
    - register_messages


tasks:
  - task_name: First Payment
#    data_class: !!python/name:etl_tasks.movie_watch.data_structures.MovieWatch
