cycles_delay: 60

kafka:
  bootstrap_servers: localhost:9092
  auto_offset_reset: earliest
  enable_auto_commit: false
  group_id: etl_service
  topics:
    - bill


tasks:
  - title: bill.created
    method: !!python/name:services.nottification_handlers.send_created_notification_to_user
  - title : bill.paid
    method : !!python/name:services.nottification_handlers.send_paid_notification_to_user

