version: '3.8'

services:
  auth_api:
    build: .
    volumes:
      - ./src/auth_api:/home/app/src/auth_api
      - ./src/auth_api/migrations:/home/app/src/migrations:ro
      - auth_logs:/home/app/logs
    env_file:
      - example.env
    entrypoint:
      - /home/app/entrypoint.sh
    expose:
      - 5000
    networks:
      - external_movie_network
    depends_on:
      - auth_db
      - auth_redis

  auth_consumer:
    build: .
    volumes:
      - ./src/auth_api:/home/app/src/auth_api
      - ./src/auth_api/migrations:/home/app/src/migrations:ro
      - auth_logs:/home/app/logs
    env_file:
      - example.env
    entrypoint:
      - python
      - auth_api/consumer/main.py
    networks:
      - external_movie_network
    depends_on:
      - auth_db
      - auth_redis

  auth_db:
    image: postgres:12.0-alpine
    env_file:
      - example.env
    expose:
      - 5432
    networks:
      - external_movie_network

  auth_redis:
    image: redis:6.2.6-alpine
    expose:
      - 6379
    networks:
      - external_movie_network

networks:
  external_movie_network:
    name: movie_network

volumes:
  auth_logs:
    external: true