@startjson
[
{
   "service":"billing",
   "login":"srv_billing",
   "password": "EvJkpM8yCTfgtIEgzx8I"
},
{
   "service":"event_to_notification",
   "login":"srv_bills_notif",
   "password": "FdbQJum5RB1kK0YSBnVr"
}
]
@endjson
