
@startuml




(*) --> "проверка сообщения на соответствие контракту"

if "observer" then
  --left->[не соттветвует ] "пропуск"
  -> (*)
else
  -->[соответствует] "назначение хендлера"
endif
if "" then
    -->[bill.paid] "отправляем чек юзеру"
    --> (*)
else
    -right->[bill.refunded] "сообщение администратору"
    -down->[bill.refunded] "чек об отмене юзеру"
    -down-> (*)
endif

@enduml





