
@startuml




(*) --> "проверка сообщения на соответствие контракту"

if "observer" then
  --left->[не соттветвует ] "пропуск"
  -> (*)
else
  -->[соответствует] "назначение хендлера"
endif
if "" then
    -->[bill.paid] "добавляем/продлеваем роль "
    --> (*)
else
    -down->[bill.refunded] "удаляем роль"
    -down-> (*)
endif

@enduml





