@startjson
[
{
   "uuid":"1e320df7-cd4b-43e4-8d9c-bdf1f8b5a7e4",
   "code":"guest",
   "title_ru": "Гость"
},
{
   "uuid":"169f17d7-63a9-4f52-a49a-20e201a6a29a",
   "code":"registered",
   "title_ru": "Пользователь"
},
{
   "uuid":"c45ea0ef-f9b4-4569-af09-9ee7b0a9c16c",
   "code":"administrator",
   "title_ru": "Администратор"
},
{
   "uuid":"065ad9e0-bb75-4127-94a6-6022e3e0a666",
   "code":"sub_practix_basic",
   "title_ru": "Practix.Стандарт"
},
{
   "uuid":"6014c570-7ee8-4636-9bca-0415442ca7b6",
   "code":"sub_practix_plus",
   "title_ru": "Practix.Плюс"
},
{
   "uuid":"2c6fb321-f240-46f8-a73a-335fe69e67ed",
   "code":"sub_practix_max",
   "title_ru": "Practix.Макс"
}
]
@endjson
