@startuml

(*) --> "проверка сообщения на соответствие контракту"

if "observer" then
  --left->[не соответвует ] "пропуск"
  -> (*)
else
  -->[соответствует] "назначение хендлера"
endif
if "" then
    -->[bill.paid] "добавляем/продлеваем роль"
    --> (*)
else
    -->[bill.refunded] "удаляем роль"
    -down-> (*)
endif

@enduml