# Generated by Django 3.2.13 on 2022-06-05 02:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAutoPay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user_uuid",
                    models.UUIDField(db_index=True, verbose_name="uuid Пользователя"),
                ),
                ("bill_uuid", models.UUIDField(verbose_name="uuid Платежа")),
            ],
            options={
                "verbose_name": "Автоплатеж",
                "verbose_name_plural": "Автоплатежи",
                "db_table": "user_autopay",
            },
        ),
        migrations.AlterField(
            model_name="bill",
            name="item_uuid",
            field=models.UUIDField(verbose_name="uuid Объекта"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("canceled", "Отменен"),
                    ("paid", "Оплачен"),
                    ("refunded", "Возвращен"),
                ],
                default="created",
                max_length=50,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="user_uuid",
            field=models.UUIDField(db_index=True, verbose_name="uuid Пользователя"),
        ),
        migrations.AddConstraint(
            model_name="userautopay",
            constraint=models.UniqueConstraint(
                fields=("user_uuid", "bill_uuid"),
                name="unique_user_bill_auth_pay_index",
            ),
        ),
    ]
