@startuml
start

:Запрос на создание платежа;

:Получить информацию об объекте покупки;

#yellow:Создать платеж. Статус __**created**__;

if (Можем ли провести автоплатеж?) then (**да**)

  :Попробовать провести автоплатеж;

else (**нет**)

  :Создать ссылку в ЮКассе на оплату;

endif

if (Получилось провести платеж?) then (**да**)

  #palegreen:Принять платеж. Статус __**paid**__;

else (**нет**)

  #pink:Отменить платеж. Статус __**canceled**__;

endif

stop
@enduml