@startuml
start

:Запрос на возврат платежа;

:Получить информацию об оплаченном платеже;

if (Получилось получить информацию о платеже?) then (**да**)

    :Попробовать вернуть платеж;

    if (Средства возвращены?) then (**да**)

      :Обновить платеж. Статус __**refunded**__;

    else (**нет**)

    endif

else (**нет**)

endif

stop
@enduml