# Переопределение настроек с помощью переменных окружения:
#     auth_api__password=bar


notification_api:
  url: http://localhost/api/v1/send/email

auth_login: notification
auth_password: notification_password

kafka:
  bootstrap_servers: localhost:9092
  auto_offset_reset: earliest
  enable_auto_commit: false
  group_id: etl_service
  topics:
    - bill
